### ISSUE TITLE
Les noms 

### ISSUE THREAD

**Issue by simon-moulin** [3devs-io/Champariz-Game#2]
Quand on mets les noms des joueurs, le premier apparaît toute la partie.
Il faudrait ajouter les règles en première page

**Comment by ReversedHourglass** [comment]
Adding rules to homepage.

**Comment by ReversedHourglass** [comment]
Fixed. https://github.com/3devs-io/Champariz-Game/commit/ba477d7b19523698165507f9eea9803fdac5e676

**Comment by ReversedHourglass** [comment]
045c1da80c5eaf642cae96632dc01c24473f65dd
